version: "3.9"
services:
  db:
    image: "postgres:14"
    ports:
      - "5431:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=todoEx
